CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name    VARCHAR(50)  NOT NULL,
    email   VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items
(
    item_id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(200)  NOT NULL,
    description  VARCHAR(1000) NOT NULL,
    is_available BOOLEAN       NOT NULL,
    owner_id     BIGINT        NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text       VARCHAR(1000) NOT NULL,
    author_id  BIGINT        NOT NULL,
    item_id    BIGINT        NOT NULL,
    created    TIMESTAMP     NOT NULL,
    FOREIGN KEY (author_id) REFERENCES users (user_id),
    FOREIGN KEY (item_id) REFERENCES items (item_id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    start_time TIMESTAMP NOT NULL,
    end_time   TIMESTAMP NOT NULL,
    item_id    BIGINT    NOT NULL,
    booker_id  BIGINT    NOT NULL,
    status     VARCHAR(50),
    FOREIGN KEY (item_id) REFERENCES items (item_id),
    FOREIGN KEY (booker_id) REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description   VARCHAR(1000) NOT NULL,
    creation_time TIMESTAMP     NOT NULL,
    requester_id  BIGINT        NOT NULL,
    FOREIGN KEY (requester_id) REFERENCES users (user_id)
);